### ISSUE TITLE
Feature Request - single WIki solutions

### ISSUE THREAD

**Issue by AnthonyMuscio** [donmor/Tiddloid#1]
Thanks so much for developing in this space. I am sure you are aware of Quinoid which provides a similar service, but there is value in alternatives and diversity.

I just wanted to voice a desired feature that would allow single wiki distribution as an app. 

TiddlyWiki allows the creation of great solutions we want to distribute to Mobiles. An example may be a journaling tool. 

Rather than force users to have to engage in an app in which tiddlywikis are one or more documents within a tiddlywiki manager it would be nice if they could be distributed as apps in their own right, their own icon and distribution method (with the wiki embedded). If successful we would see a boom in tiddlywiki solutions available in the app stores.

There seems to me to be two ways to do this

- Provide a method to provide icon to specific wiki within a manager app
- A way to create a Wiki with a single tiddlywiki embeded - can be forked for each solution developed into a new app.
- An app designed to contain a single TiddlyWiki without the management features, that only requires the TiddlyWiki to be specified, thus loaded perhaps from an internet address the first time only, or with a forced reload. Ideally you could still manage save and export.

Thanks for considering this idea

Tony

**Comment by donmor** [comment]
New version with shortcut feature is in progress

**Comment by donmor** [comment]
New release version published

**Comment by AnthonyMuscio** [comment]
Hi, I tested creation of home screen icons and it works well. Quite fast as well.

Thanks very much for that. I will continue to test further.

**Comment by AnthonyMuscio** [comment]
donmor,

If I have more than one shortcut the second will replace the first in Tiddloid. If there are unsaved changes in the first they will be lost. Autosave mitigates this a lot but it is still possible.

Would it be too much to ask that Tiddloid could open more than one instance of itself when activated from a shortcut, one for each wiki?. I suppose it would be desirable NOT to open multiple instances of the same wiki.

I have no idea of how complex this would be but thought I would share a desirable feature.

Regards
Tony

**Comment by donmor** [comment]
Hi Tony,
Sorry  I haven't found the way to open a new instance from each shortcut. I'd find a way to solve this problem (or probably fails 'cause I'm not a pro)

**Comment by AnthonyMuscio** [comment]
Donmore,

For some reason I deleted a shortcut, replaced a wiki and now I cant because I get the Message "Failed to create shortcut". I am not sure how to debug this - I removed all existing  shortcuts with no success.

Regards
Tony

**Comment by AnthonyMuscio** [comment]
I may also ask if we may discuss the original thread subject. The desktop shortcut helps but not is all I am asking.

**Feature Request - single WIki solutions**

Actually I my have a business proposition here. I would like to see if we could get an application that acts as a template such that we can generate an app that can go into the appstore after loading it with a single tiddlywiki. As a result it would not need a directory, only the ability to create a shortcut, and we can preset backups to a maximum number.

Such a solution would make it possible for anyone who can build a feature rich TiddlyWiki to turn it into an android app and start selling it in the appstore, and the community could publish free apps to publicise tiddlywiki.

What do you think?

I understand you are no expert but you know more than me on the app side.

**Comment by donmor** [comment]
Sorry for no replying but I'm busy on looking for a job since I'm graduating from collage.

I may continue on this project in this year.

**Comment by donmor** [comment]
A new release have been published to fix some bugs.
