### ISSUE TITLE
sometimes can't save tiddlywiki correct format

### ISSUE THREAD

**Issue by sakagsakag** [donmor/Tiddloid#11]
![Screenshot_2020-09-08-11-01-16](https://user-images.githubusercontent.com/70927141/92425705-ff749000-f1c2-11ea-9b52-3c00ffec4670.png)

both html file after saving used tiddloid. a2old.html can 't re open after saving.
i dont know what timing ok or ng.
using android 6.

**Comment by donmor** [comment]
I can't get what is going wrong from what you posted. Any more information?

**Comment by donmor** [comment]
Too long time waiting for a response. Closing.

**Comment by donmor** [comment]
Now there're more people reporting this. Moving to #23.
