### ISSUE TITLE
version 1.4 debug works well

### ISSUE THREAD

**Issue by IngoBelka** [donmor/Tiddloid#15]
I'm using version 1.3.6 since it came out. It worked very well all the time.
Now I've installed 1.4 and there are no problems at all. All works smooth for me.
Thank you for Tiddloid!

**Comment by donmor** [comment]
Thanks for your using and testing. I'm glad to see that my apps are helpful.

One more thing is that issues are for bug tracking rather than comments. You can post them on [TiddlyWiki's discussion page](https://github.com/Jermolene/TiddlyWiki5/discussions).
