### ISSUE TITLE
Freezes on blank screen when importing/opening

### ISSUE THREAD

**Issue by tedric42** [donmor/Tiddloid#16]
Hi, I'm new to TiddlyWiki and Tiddloid. I am having trouble importing and opening wiki files. Sometimes it works but more often the app gets hung up on a blank screen (sometimes white, sometimes black). This happens when importing from both local and Google Drive storage, and when opening from withing Tiddloid and from a shortcut. The one time I tried making changes to a Drive-hosted wiki, the upload process stalled too. I'm now trying to re-import that wiki and try again, but haven't got it to open yet.

I'm using the latest Tiddloid release on Android 9 with a Moto X4. Any help is appreciated!

**Comment by tedric42** [comment]
On further testing it looks like these processes _are_ happening even when they appear frozen (at least sometimes) but they are taking an unusually long time. Like 5+ minutes to open a wiki (long enough to trigger "This app isn't responding" warnings), 15+ minutes to sync a 3MB wiki file back to Drive.

**Comment by virtadpt** [comment]
Maybe a progress bar would be helpful?  A HEAD request to get the size of the Tiddlywiki file, and bytes downloaded so far to calculate the percentage?

**Comment by donmor** [comment]
Hmm...That's weird...I had never repreduced this problem. Will it freeze if built from source? I think the best way to find the code where the app freeze is using break points. You can have a try if you're familiar to Java.

**Comment by donmor** [comment]
> Maybe a progress bar would be helpful? A HEAD request to get the size of the Tiddlywiki file, and bytes downloaded so far to calculate the percentage?

The freezing happens in the initializing part, before the progress bar can work, as @tedric42 said. But it's unusual to see that...

**Comment by donmor** [comment]
Sounds like some kind of IO malfunction blocked the TiddlyWiki validity check. Have you tried on other devices?

**Comment by tedric42** [comment]
I'm not familiar with Java and don't know how to build from source unfortunately. I haven't tried other devices yet but it turns out I'm getting a new phone today so hopefully that will solve the issue.

**Comment by virtadpt** [comment]
> The freezing happens in the initializing part, before the progress bar can work, as @tedric42 said. But it's unusual to see that...

Oops.  My bad.

**Comment by tedric42** [comment]
I got a new phone (Motorola One 5G) and the issues noted above are not happening. However I am having other problems with Tiddloid now :) I'll start a new issue(s) as needed.
