### ISSUE TITLE
Listed as Tiddloid Lite on f-droid

### ISSUE THREAD

**Issue by Younes-L** [donmor/Tiddloid#17]
Tiddloid Lite on f-droid : https://f-droid.org/en/packages/top.donmor.tiddloid/

Just curious , I've looked at the build metadata and nowhere does it mention "Lite" so I'm puzzled,

thought I'd report it here in case it's important and not intentional.
Kudos for the great work btw 👍

**Comment by donmor** [comment]
Actually it's Tiddloid with wrong description assigned. I'll try to fix it soon.

**Comment by donmor** [comment]
Fixed in 2.1.0.
