### ISSUE TITLE
Local Iframes

### ISSUE THREAD

**Issue by TowelSniffer** [donmor/Tiddloid#19]
Hi,

I use a lot of local iframes in my TiddlyWiki however local HTML files won't load with tiddloid. 

for instance:
```
<iframe class='timerIframe' src='files/Timer.html?setTime=25'></iframe>
```
or
```
<iframe class='timerIframe' src='./files/Timer.html?setTime=25'></iframe>
```
returns blank

[here](https://drive.google.com/drive/folders/1mINNZDDXSnhlpVe-3hEwYCJ3b1cT5BP8?usp=sharing) is an example setup that is similar to what I am trying to achieve

**Comment by donmor** [comment]
You're supposed to add the whole folder containing your `index.html`, or import the file using legacy mode. See `Readme.md` for details.

**Comment by TowelSniffer** [comment]
Hey man thank you for your help. Adding the folder would not work for me and just kept crashing but I fixed it by removing a large zip file I had inside it.

**Comment by donmor** [comment]
What size is the zip file? Did it crash immediately or just freezes?

**Comment by TowelSniffer** [comment]
The zip was about 200 mb but I have a 30 mb PDF that also seems to cause it to freeze. 

Basically it just freezes for about 4 seconds with a blank screen and then crashes.

**Comment by donmor** [comment]
Is it possible for you to get the stack trace on crashing? I'll test with some big file later, though.

**Comment by TowelSniffer** [comment]
I will have time tomorrow so I will see if I can figure that out. The pdf was I lot bigger than I remembered, actually 150 mb not 30, but I will have a better look tomorrow.

**Comment by donmor** [comment]
Problem has been located. Will be fixed in next version.
