### ISSUE TITLE
Unwanted Warning on exit

### ISSUE THREAD

**Issue by AnthonyMuscio** [donmor/Tiddloid#2]
Hi,

After making a change in  a TiddlyWiki, and auto save saving it, I get the yellow notification any attempt to use the top left arrow to return to tiddloid's menu results in the following message.

**Attention**
Are you sure you want to quit?
Please make sure all your
Modifications have being saved
                           **CANCEL OK**

I have seen this in other circumstances like BOB and expect it is possibly in the core or the saving mechanism in use. Perhaps it is the autosave failing to unset a dirty indicator.

**Would it be possible to stop this message occuring?**

**Comment by donmor** [comment]
I'm sorry that I havn't found a way to get the status of dirty indicator in the TiddlyWiki.

I may ask Jeremy for help later this year.

**Comment by AnthonyMuscio** [comment]
You are not the only one. I will see what I can find.

**Comment by donmor** [comment]
A new release have been published to bring this feature.

**Comment by AnthonyMuscio** [comment]
A Quick test in Tiddloid on a copy of tiddlywiki.com v 5.1.21 suggests this is fixed, So I am closing this.

Thanks heaps
