### ISSUE TITLE
Android 11 status bar fails to restore after exiting

### ISSUE THREAD

**Issue by Dialga** [donmor/Tiddloid#20]
After exiting tiddloid from a shortcut to a tiddlywiki file, the status bar is not restored on Android 11.
Expected behavior is that the status bar returns.

**Comment by donmor** [comment]
Okay. Did you mean:
You opened a wiki from main screen -> back to desktop -> open another via a shortcut (with status bar hidden) -> close it and back to the wiki previously opened? If so, I think I got what is wrong. I'll try to fix it soon.

**Comment by Dialga** [comment]
No this is not on the desktop, I've opened it from the shortcut on the app screen then tapped back to exit.

**Comment by donmor** [comment]
Any screenshots? I'm trying to reproduce it but nothing wrong happened yet.

**Comment by Dialga** [comment]
I'll add one soon.

The exact steps:
1. Create new tiddlywiki file, save it without name
2. Back in tiddloid long tap on the created tiddlywiki
3. then tap "create a shortcut" note the path is (invalid).html
4. "shortcut added successfully" pops up even though add is not tapped yet
5. tap on Add "shortcut to x added to home screen"
6. tap back to exit tiddloid
7. android status bar remains hidden

Seems to occur only after starting tiddloid after a period of non use, and creating a new tiddlywiki file.

**Comment by donmor** [comment]
Hmmm...Where did you put the new file in? Is it created on a cloud drive, or the internal storage?

**Comment by Dialga** [comment]
external sd card

**Comment by donmor** [comment]
Hmm.. There's no string resource of "(invalid)" in the app... So you created a file without name and the system gave the file a name `(invalid).html`?

**Comment by Dialga** [comment]
yes

**Comment by donmor** [comment]
Operated as you did but nothing weird happened... In fact I had never made the status bar hidden on the main screen... Even if the status bar is hidden under landscape mode, it'll restore on entering the main screen...

**Comment by donmor** [comment]
What phone are you using?

**Comment by Dialga** [comment]
Samsung Galaxy S10 with Android 11.

**Comment by donmor** [comment]
When did the status bar disappear for the first time during the reproduction?

**Comment by Dialga** [comment]
First install and after reboot.

**Comment by donmor** [comment]
You mean... The status bar disappeared on entering the app, and never come back?

**Comment by Dialga** [comment]
Yes

**Comment by donmor** [comment]
That's completely abnormal... I had never seen that before even on Android 11 AVD...
Are you able to get logcat from your phone?

**Comment by donmor** [comment]
It's weird to say that but... it is possible that some of system APIs was implemented differently between AVD(pixel) and samsung's os... The splash activity hides the bars, and is replaced by the main activity, which, by default, makes the bars shown. But if the UI is not reset upon changing activity... What if entering the app and change to landscape, then back to the desktop while keeping the phone horizontal?

**Comment by Dialga** [comment]
> Any screenshots? I'm trying to reproduce it but nothing wrong happened yet.

Attached.

![Screenshot_20210802-201220_One UI Home](https://user-images.githubusercontent.com/5157928/128132446-944cc71c-fcb6-4010-a9d8-43e6d2247c70.png)



> It's weird to say that but... it is possible that some of system APIs was implemented differently between AVD(pixel) and samsung's os... The splash activity hides the bars, and is replaced by the main activity, which, by default, makes the bars shown. But if the UI is not reset upon changing activity... What if entering the app and change to landscape, then back to the desktop while keeping the phone horizontal?

I noticed if I try to add another widget then the status bar returns.

**Comment by donmor** [comment]
Now you can checkout the latest 2.2.0-pre version [here](https://github.com/donmor/Tiddloid/releases/tag/2.2.0-pre) (This is a pre-release with a debug package)

I refactored the splash screen in recent commits, and added WebDAV support which can be helpful to avoid problem like #23 .

**Comment by donmor** [comment]
Is your problem solved? I may close this if no response received for a long time.

**Comment by donmor** [comment]
No more reports for nearly a year. Closing this. Reopen it if you're still concerned.
