### ISSUE TITLE
Tiddloid loses track of google drive tiddlywikies. 

### ISSUE THREAD

**Issue by Griffork** [donmor/Tiddloid#21]
I have a tiddlywiki saved in google drive, it's set to starred and available offline. I can import it into tiddloid just fine, but if I close and open the app and try to open it from the recents menu (the main screen) I get an error saying that it doesn't exist. If I import it again the file is still shown to be at the same location. Maybe google drive updating the file is causing the link to break?

I believe I'm using the tiddloid 2.0 beta, but the about page doesn't include version information 😕.

**Comment by donmor** [comment]
I'm not using GDrive because, uh, some restrictions.
Did your file on GDrive updated upon saving? Or the GDrive app is not running when clicking the entry in the main screen?

**Comment by Griffork** [comment]
Did your file on GDrive updated upon saving? > I don't know when tiddly drive updates the file, this happens regardless of whether or not I make changes to the file on the phone or if I press the red check (save) button. Autosaves are turned on.

Or the GDrive app is not running when clicking the entry in the main screen? > Not really sure what you mean by this, but it happens regardless of whether or not I have GDrive open (and I think it's always running in the background?).

Exact repro steps are as follows:

1. I go into tiddly wiki and add a tiddler which happens to be in a GDrive controlled folder. 
2. I then open the tiddler (which works). 
3. I then close the app. 
4. I then immediately open the app and the tiddler is linked in the main menu (because I added it before). 
5. I click on the tiddler link in the main menu and get an error saying the file was moved or deleted and the link in the main menu deletes itself. 
6. I then press the add tiddler button and the file is showing in the *exact same location* it was in last time and I can add and open and close it to/from the main menu fine until I close the app again.

So the file hasn't moved, it's permissions haven't changed it's still there and accessible, it just seems that when tiddloid is loading it's messing up the link. I'd guess it's loading a different path than the one I originally added (maybe treating it as an absolute path instead of relative to the GDrive folder or something).

**Comment by donmor** [comment]
Fine... I'll try to debug it if I can make Gdrive work in the avd.
Did you tried clicking "no" in the auto-remove prompt, keeping the link in the list, and add the file again? If a new entry's created, it means the uri's corrupted; If there's a "wiki already exists" prompt and the link's fixed, then it's a permission problem.

**Comment by Griffork** [comment]
I did what you asked, clicking cancel in the remove prompt and added the file again, a new entry is created.

**Comment by donmor** [comment]
Finally I got to use GDrive on my AVD, but... I can't even create the file directly from Tiddloid. The debugger reported an exception that RW mode is not supported. Creating the file by uploading from local did work though, writing permission successfully granted.

**Comment by donmor** [comment]
Fine... It seem that Google put a restriction on 3rd party apps that uses SAF to access the drive, as there's something called Google Drive SDK for Android, but the docs are 404ed... I'm afraid there's no way to make this app to have full access to GDrive.

**Comment by donmor** [comment]
Nutstore (in China) is tested to give full access via SAF. Another 3rd-party friendly choice is OneDrive, it allows every operations via SAF EXCEPT DELETING.

**Comment by donmor** [comment]
Deleted the file via Tiddloid successfully... So GDrive bans creating while OneDrive bans deleting... What the...

**Comment by mikjsmith** [comment]
I think this is similar to this solution for PasswordSafe: https://sourceforge.net/p/passwdsafe/wiki/SyncGoogleDrive/

**Comment by donmor** [comment]
So it means I have to use Google's proprietary GMS packages? I consider Tiddloid as a free software, or some people called libre software, so I won't do that.

**Comment by donmor** [comment]
Are you using other cloud services that support WebDAV? Now you can checkout the latest 2.2.0-pre version [here](https://github.com/donmor/Tiddloid/releases/tag/2.2.0-pre) (This is a pre-release with a debug package)

**Comment by donmor** [comment]
No more reports for over a year. Closing this. Reopen it if you're still concerned.
