### ISSUE TITLE
Full Screen Lead to Wide Lode

### ISSUE THREAD

**Issue by Darleey** [donmor/Tiddloid#22]
Version 2.1.1
If I try to enble the full screen [ ], The window would display in another mode. It would make it harder to operate... Is there a way to make it behave like it in web browser?

BTW, you did a great job !

**Comment by donmor** [comment]
This mode is for people who want an immersive experience. You can still quit a wiki using softkeys.
I'll consider if this cpuld be added into the app.

**Comment by Darleey** [comment]
Sorry, I didn't describe the situation clearly.

Immersive experience is what I want.

While if I tries to experiences it in a mobile phone, the screen changes from vertical mode to the horizontal mode. Which would make it  an unpleasant experience.

Maybe it needs a function to adjust the device. Or just add a setting for the user to config themselves.

**Comment by donmor** [comment]
I see. I originally implemented this to enable fullscreen on embedded videos.
You can just hide the toolbar to make it immersive. See the FAQ for instructions.

**Comment by Darleey** [comment]
As you see, the html page generated by Tiddloid is the same as the one provided by official net. I failed to find the option 'Tiddloid Tweaks'

![Screenshot_20210802-210147.jpg](https://user-images.githubusercontent.com/7878586/127866187-da36bb33-fd5c-404c-af1a-2717a38dd29d.jpg)

**Comment by donmor** [comment]
https://github.com/donmor/Tiddloid/releases/tag/2.1.0
It will be uploaded with the apk only if updated. You may find it in previous releases.

**Comment by Darleey** [comment]
thanks a lot, it works ~

**Comment by donmor** [comment]
Closing this since there's no recent post.
