### ISSUE TITLE
Using external images

### ISSUE THREAD

**Issue by eduvf** [donmor/Tiddloid#24]
I don't know if it has to do with the way Tiddloid handles files, but it seems it cannot display external images (not embedded within the HTML file). Specifically, I'm trying to load some PNGs and JPEGs inside a folder located in the same directory as the HTML file (like [img[relative/path/to/image.png]]). There's [this](https://tiddlywiki.com/static/ExternalImages.html) other method, but it doesn't work either...

Thanks!

**Comment by donmor** [comment]
You can use directory mode or legacy mode. See the readme for details.

**Comment by eduvf** [comment]
Thanks!
I've ended up using the 'add folder' feature, that let's you do that with an index.html file

**Comment by donmor** [comment]
Are you using cloud services that support WebDAV? Now you can checkout the latest 2.2.0-pre version [here](https://github.com/donmor/Tiddloid/releases/tag/2.2.0-pre) (This is a pre-release with a debug package)

**Comment by donmor** [comment]
Hmm... I just tried legacy mode and everything goes well. What version of system and Tiddloid are you using?

**Comment by gMakaan** [comment]
It will be cool to have an in-app hint when loading a new wiki file - "if your wiki have external linking to local media/scripts - use legacy mode" or some similar approach.

**Comment by donmor** [comment]
> It will be cool to have an in-app hint when loading a new wiki file - "if your wiki have external linking to local media/scripts - use legacy mode" or some similar approach.

In fact it is written in FAQ :)

Sounds like everything is done. Closing.
