### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#26]
Hi, I'd like to add a process that will start a nodejs wiki (using some nodejs package) that will serve a selected folder in the /media , where would you recommend I modify it?

If you think this is too heavy for Tiddloid, I can make a forked version in the https://github.com/tiddly-gittly instead of PR. I just start learning Java and Android, so I may need some help from you, maybe in the Discord channel?

As you can see from my TidGi app, I'm a nodejs wiki user, so I hope I can use nodejs wiki cross platform, thanks!

**Comment by donmor** [comment]
It's not necessary to serve node.js inside the Tiddloid. Instead you can install Termux, which can be found on F-Droid, and deploy TiddlyWiki using npm. Then you can access it by `http://localhost:<port>/`(you can't use 80 without root) and add it to Tiddloid by sharing the page.

**Comment by donmor** [comment]
话说你也是国人吧(´▽`ʃƪ)

**Comment by donmor** [comment]
你准备用Java File 还是 Storage Access Framework？前者兼容性最好但要用户端手动提权，后者。。当初加SAF目录模式时几乎把核心逻辑重写了一遍。。另外最近安卓11出现了写入文件时残留上一版本末尾内容的恶性bug。。不得已搞了WebDAV支持，又双叒叕重写一遍(ಠ .̫.̫ ಠ)

**Comment by linonetwo** [comment]
你好！那可以 QQ 群里聊，你没加 Q 群吗 946052860

我准备用 SAF，然后数据就存 media 文件夹里，应该可以吧，我觉得这个还可以接受？我只简单研究过这个 CleverRaven/Cataclysm-DDA#49310

「手动提权」指的是弹个框允许一下就行？好像 Android11 之后不行了吧，非特定应用，连弹框的机会都没有了。

我想加内置 nodejs 支持是因为希望非技术用户也能一键使用，就像早期我分享的 nodejs 桌面部署文章也被吐槽很复杂，后来我做了太记才有了更多用户。

**Comment by linonetwo** [comment]
WebDAV 我应该暂时用不上了，毕竟我都是多文件 nodejs 版的，这个没法适配 webdav 吧？如果可以的话那就好了。

**Comment by linonetwo** [comment]
我用 nodejs 版的一大原因是：方便用子wiki来保存隐私信息在本地，然后发布公开信息到博客，模拟 notion 发布博客的用法~

**Comment by donmor** [comment]
提醒一下，SAF是无法实现File方式的目录结构的。。你要弄的话只能自己实现一个或者魔改现有的nodejs库。。
有一点你说对了，SAF目录模式和WebDAV都是先同步到`/data/user/0/top.donmor.tiddloid/cache/<id>`下面再加载的，所以。。话说SAF在安卓11上有bug这个还没解决呢。。

**Comment by donmor** [comment]
#23 #25 有人已经提issue了

**Comment by donmor** [comment]
话说太微这个fork从一开始就去掉了单文件支持的吗😂我保存首页结果打不开了

**Comment by donmor** [comment]
11还是可以申请权限的，API29及以下的应用直接弹窗，升30要改一下代码，申请权限时直接弹出应用设置页面

**Comment by linonetwo** [comment]
> SAF是无法实现File方式的目录结构

这个我晕了，所以没法直接把文件夹用 git 或者 syncthing 之类的完整同步到 /media/xxx 里，然后用 SAF 获取整个文件夹权限，提供给 nodejs 进程读取吗… Android 比桌面端真是麻烦不少呀

**Comment by linonetwo** [comment]
> 先同步到`/data/user`

话说不应该是 /media 文件夹吗

**Comment by donmor** [comment]
/media是什么年代的事了。。反正我开始接触安卓开发时，内部存储空间就是/storage/emulated/0/的了。。现在的安卓早就沙箱化了，我们用的内部存储在代码里算外部存储，划出/storage/emulated/0/Android/data/<包名>/给应用，/data/user/0/<包名>这个才是内部存储，这两个不需要申请权限而且可以随着卸载自动删除，其他目录才需要申请权限或者调SAF

**Comment by donmor** [comment]
一般我缓存文件都搞内部，免得被一些申请了存储的app扫盘。。除了SAF单文件备份和failsafe为了能直接拷出来放在外部存储里

**Comment by donmor** [comment]
端口号自己取一个就行，除非和别的冲突，可以通过使用配置tiddler指定一个；
node模板的话官方版我只知道可以从npm部署出来 只添加现有目录的话可以不考虑
SAF或者WebDAV需要同步到内部，最好放在内部存储，然后可以直接访问无需申请权限
node部分能不造轮子就不造
http一定要只监听localhost(127.0.0.1)不然同一个wifi甚至ipv6的移动网络都能连上
如果你足够牛叉可以魔改node库的话也许可以砍掉http直接把bytearray拿给WebView渲染，类似nw.js那种

**Comment by donmor** [comment]
这一波预计工程量很大而且以你为主导（我比较懒，要不是安卓11的bug我都懒得搞WebDAV😂），一旦完成足够把Tiddloid直接推上到3.x版本号了

**Comment by linonetwo** [comment]
如果通过webdav或者git和电脑端同步的话，那的确不需要考虑存储权限了。我之前考虑存储权限是因为想要不要用 syncthing 和电脑端同步。
然后 media 那个我是看官方文档看的，可能他们观念比较老吧。

那我先在内部存储搞，用webdav把wiki拉过来。

**Comment by linonetwo** [comment]
老兄，我想了想还是开发一个 p2p 同步插件简单点儿，也更节能，毕竟在手机上跑 nodejs 可能太耗电了，详见 https://talk.tiddlywiki.org/t/what-will-happen-if-you-use-two-sync-method-together/2813

**Comment by donmor** [comment]
嗯扫码的话其实已经可以了的，随便个浏览器扫码打开wiki页面然后点分享把url推给Tiddloid，然后直接保存新文件或者覆盖
不过要是覆盖的话又绕不开安卓11的bug。。😂
要是自己有服务器可以架设node的话可以把node版开起来然后网址推过来打开，然后右上角保存按钮里会多出一个保存为链接的选项，这样就把node站点固定在主页上了，缺点是全程联网而且需要服务器

**Comment by linonetwo** [comment]
太记App是会在本地启动一个服务器，我现在手机上临时用就是扫太记上的二维码浏览器打开。这样的确就是走到地铁里就不好使了，而且回家之后家里的 ip 肯定跟公司里的不一样，就没法同步给家里。所以保存为链接应该不适用于这个场景。

所以我才希望能把 url 先覆盖到Tiddloid本地变成HTML版，等到家了再把HTML推给家里的太记App…

我先看看能不能搞出 p2p 同步插件，如果能的话就只需要第一步「直接保存新文件」，之后就能靠p2p在手机电脑之间同步了。

**Comment by linonetwo** [comment]
后续从电脑往手机同步，如果不方便覆盖的话，或许 Saver 插件可以把一个 url 里的 wiki 内容直接覆盖到本地 wiki 里？不知道 saver 能不能做到这一点。

**Comment by donmor** [comment]
只要是用到SAF就完犊子。。除非搞一个legacy的wiki用来同步

**Comment by linonetwo** [comment]
准备用插件来和太记同步了，不搞移动端nodejs了，先开发完插件用一段时间看看
