### ISSUE TITLE
arrow button with no function

### ISSUE THREAD

**Issue by IngoBelka** [donmor/Tiddloid#28]
Hello,

first thank you for Tiddloid, I use it each day with a great pleasure.

The arrow button on the left above corner close to the tiddlys name has no function anymore. Is this intended?

**Comment by donmor** [comment]
Are you using a release version, or a pre-release?

**Comment by IngoBelka** [comment]
I'm using version 2.2.0 from F-Droid. I see this behavoiur on my Huawei tablet as well as on my Xiaomi cellphone.

**Comment by donmor** [comment]
Gosh... So F-Droid fetched my pre-release code and got it built... The 2.2.0 is not published as a release yet. Try to downgrade to the latest stable release `2.1.1` or wait for another update. I'll figure out why the ore-release was unexpectedly built.

**Comment by IngoBelka** [comment]
While I did not find any other problems, I'll wait for the next update.

**Comment by donmor** [comment]
Solved.
