### ISSUE TITLE
Choosing starting Template

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#31]
In my https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template I have notion like theme and CPL (See https://talk.tiddlywiki.org/t/shall-i-recommand-cpl-library-with-200-tw-plugins-to-the-tiddlywiki-website/2840 ) set up.

I hope this template can help more users get into tw, to make tw popular than the Obsidian. (most people have trouble finding and configuring plugins and settings to make their wiki powerful like Ob, they said tw is too complex).

So I think if there is a template chooser when creating wiki in Tiddloid, it will be better. I will also implement this template chooser in the https://github.com/tiddly-gittly/TidGi-Desktop .

**Comment by linonetwo** [comment]
Or we can make a template with CPL (https://talk.tiddlywiki.org/t/shall-i-recommand-cpl-library-with-200-tw-plugins-to-the-tiddlywiki-website/2840) installed, so at least installing plugins won't be more complex than Obsidian.

**Comment by donmor** [comment]
嗯其实从1.x就有类似的功能，就是Fork
2.x改成了从分享的文本中提取链接然后加载页面，然后点击保存按钮调用SAF选择器保存文件
非要内置一个的话。。为了随时更新，需要搞个静态服务器（比如pages）放入一个配置文件，里面保存各个模板的信息、官网、empty文件地址之类，并且指定语种，自动根据终端语言筛选（毕竟咱们不希望看到一堆西语法语德语模板堆在里面，老外也用不着中文模板。。语种可以指定多个，也可以直接设定成全语种适用）
这个想法估计还是需要和上游项目那帮人讨论讨论😂比如TiddlyDesktop需不需要也引入这个机制之类
不然就只能中文区自己玩了🙃

**Comment by donmor** [comment]
也可以考虑由你们直接Fork一个版本出去，包名改掉，然后各种本土化魔改😂毕竟Tiddloid需要适配全世界大多数使用国际版的人，不方便大搞一些本土化修改

**Comment by donmor** [comment]
话说太微现在用的是什么模板？是国际版中文模板还是Fork出来的改版？

**Comment by donmor** [comment]
话说你们在netlify上的教程不知道魔改了哪里，一保存本地就提示缺少js打不开了😂

**Comment by donmor** [comment]
官方node版还是可以用工具栏保存按钮强行克隆到本地然后随便保存的😂

**Comment by linonetwo** [comment]
那个用了 lazy JavaScript ，所以只能通过工具栏那个按钮保存，应该可以吧。

关于模板列表，我们之前讨论过，可以搞一个类似现在 CPL 那种（或者 tiddlylinks 网站也是），大家可以往里面PR填自己的模板的HTML地址，然后 github action 从这个 wiki 里提取出所有地址和介绍文本，每天12点整打包变成一个 JSON发到github pages 作为 CDN，然后 TidGi 和 Tiddloid 可以拉取这个 JSON 来显示这些第三方模板。可以根据语言之类的字段来筛选一下。

这个模板站我们搞 CPL 的准备有空搞一下。

当然tiddloid的列表里可以默认显示一个官方空白模板，这个应该是内置的吧。

**Comment by linonetwo** [comment]
太记用的是一个内置了一大堆插件的 notion 模板，来让新用户更好上手，方便宣传。

**Comment by donmor** [comment]
不戳～模板列表要不要试试推广到上游国际版？

**Comment by linonetwo** [comment]
应该类似 [https://tw-cpl.netlify.app/](https://tw-cpl.netlify.app/) ，国内国外的都可以自由加进去，也可以帮别人加（现在很多弃坑了的外国人的插件就是我们帮忙加进去的）

**Comment by donmor** [comment]
到时候看看能不能在国外宣传一下，或者并入主线里面🤔

**Comment by linonetwo** [comment]
CPL 吗，最近在问 [https://talk.tiddlywiki.org/t/shall-i-recommand-cpl-library-with-200-tw-plugins-to-the-tiddlywiki-website/2840/7](https://talk.tiddlywiki.org/t/shall-i-recommand-cpl-library-with-200-tw-plugins-to-the-tiddlywiki-website/2840/7)

如果你是说模板列表的话，我们也会像 CPL 一样先做起来，然后之后也 PR 给官网吧

**Comment by donmor** [comment]
``` JSON
{
    "locale":{    // TW现有的所有区域和语言
        "zh-Hans":{    // 以简中为例
            "name":"中文 - 中国",    // 本语言中的名称
            "alias":[    // 别名，对应各种系统下获取的locale字串
                "zh-rCN",    // Android
                "zh-CN",    // 标准
                "zh-CN.UTF-8" // Linux/Unix
            ]
        }
    },
    "templates":[    // 模板列表
        {
            "name":"TiddlyWiki",    // 名称
            "locale":[    // 所有兼容的locale，筛选依据之一
                "*-*"    // 通配符，适用所有区域的所有语言
            ],
            "desc":"Official release",    // 描述，有长度限制
            "icon":"uri/base64",    // 图标，推荐尺寸48x48
            "uri":"https://tiddlywiki.com/empty.html",    // empty.html文件URL
            "lastUpdate":1234567890,    // Unix时间戳，action根据uri字段拉取文件并获取时间戳，筛选依据之一
            "version":"5.1.22"    // 试运行拉取的HTML文件并获取内核版本，筛选依据之一
            "valid":true    // 获取不到版本信息时设定为false，客户端自动屏蔽这个模板
        }
    ]
}
```
试做了一个json结构，希望可以作为参考

**Comment by donmor** [comment]
目前还没建好模板列表的话，回头我先发布2.2.0吧，那部分暂时屏蔽掉

**Comment by linonetwo** [comment]
你先发布吧，我还没搞好…

**Comment by linonetwo** [comment]
我优先把太记和tiddloid同步数据的js插件写了

**Comment by linonetwo** [comment]
既然同步数据搞定了，我来写这个，我先放在 [https://talk.tiddlywiki.org/t/choosing-starting-template-a-tw-edition-wiki-template-list-api-json-example/2974](https://talk.tiddlywiki.org/t/choosing-starting-template-a-tw-edition-wiki-template-list-api-json-example/2974) 公示一下

**Comment by donmor** [comment]
我想了一下，打算drop掉这个功能了，第三方的内容过于不可控，搞不好被举办。。或者要我提供ICP什么的
至于tw官方搞事。。那我可能会主动下架跑路罢^q^

**Comment by linonetwo** [comment]
那没事，反正可以从太记同步过去，我在太记里加上，然后之后用户可以太记那边新建特色模板然后导过去呗

**Comment by linonetwo** [comment]
希望能把扫码加载 localhost 网页导入手机的流程优化一下呀 https://www.bilibili.com/video/BV1Wg411r7Yu

**Comment by donmor** [comment]
这边打算复活Legacy模式，和webdav做到一起

**Comment by donmor** [comment]
另外有人发了高版本乱码的解决方案，回头搞一下试试

**Comment by linonetwo** [comment]
webdav 应该没法用于扫码导入，因为桌面上大多数用户是 nodejs 多文件版的。目前可以手机相机扫码在手机浏览器打开，然后发送分享到 tiddloid，但是会闪退崩溃。
