### ISSUE TITLE
QQ channel and QQ group

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#32]
点击链接加入话题子频道【Tiddloid （Android端应用）】：https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&inviteCode=PXoyG&appChannel=share&businessType=10&from=246610&biz=ka

这是QQ频道的链接，你看要不要加在 readme 里面，这样用户可以加进来讨论。国内现在比较好用的就是QQ频道了，像微信群那样加人不方便 同时又可以有机器人自动答疑。

**Comment by donmor** [comment]
呃 我的TIM打不开😂

**Comment by linonetwo** [comment]
毕竟是QQ的功能，比较重，不会放进tim吧
