### ISSUE TITLE
Share file/image to tiddloid, using system share menu, and choose which wiki to share

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#33]
提议 Tiddloid 加一个接受分享的功能，这样图片就能直接分享发到wiki里了，像QQ接受分享之后选择分享给哪一个好友一样，可以再选择一下分享给哪一个 wiki。

分享后就相当于拖入内容，会弹出 import 界面。

那也可以把一个网页的链接share过来，自动变成import了新条目，之后可以在电脑上打开稍后读。

**Comment by donmor** [comment]
嗯 回头看看

**Comment by linonetwo** [comment]
https://zhuanlan.zhihu.com/p/385017593 现在各种知识管理应用的分享到功能都很便捷啦

**Comment by donmor** [comment]
2.3.0整好了，可以试试

**Comment by linonetwo** [comment]
哇塞，真的可以哦，是默认分享到最近用的那个 html 里吗？

**Comment by donmor** [comment]
是自己选一个然后长按，选项里勾上，这样后台没开页面的时候直接打开这个页面添加
如果已经在后台打开了就直接添加了
