### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#34]
需要一个方便国内用户打开的，宣传用的网页
<img width="719" alt="截屏2022-03-26 16 38 40" src="https://user-images.githubusercontent.com/3746270/160231770-bae2163a-2143-41db-bb94-f1a95e1b5a07.png">

Github 页面不一定打得开。

**Comment by donmor** [comment]
gitee有镜像，酷安页面上有链接

**Comment by linonetwo** [comment]
感觉酷安的页面可以用 https://www.coolapk.com/apk/top.donmor.tiddloid
