### ISSUE TITLE
webview debug

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#37]
![Screenshot_2022-04-14-23-17-40-686_top.donmor.tiddloid.jpg](https://user-images.githubusercontent.com/3746270/163421049-3bc526cf-c018-4c7f-af55-8ee206234013.jpg)

**Comment by donmor** [comment]
这是在哪一步出来的？

**Comment by linonetwo** [comment]
我的同步插件，在js里用get到的HTML全量覆盖本地wiki后，会报一个错，但是我没法看到报错栈，希望在之后发布的app里能开一下 webview 的 debug 开关

**Comment by linonetwo** [comment]
<img width="1353" alt="截屏2022-04-14 23 20 19" src="https://user-images.githubusercontent.com/3746270/163421503-94cf615c-2af3-4e4c-a884-f62d7dfc8eac.png">

以后手机电脑同步方便多了

**Comment by linonetwo** [comment]
我看公司里的文档，应该有这一个方法打开

 webView.setWebContentsDebuggingEnabled(true);

**Comment by donmor** [comment]
那就加个检测包是debug还是release，debug版开启

**Comment by donmor** [comment]
到时候拉源码编译debug版就行

**Comment by linonetwo** [comment]
也可以，不过为啥正式版不开呢，这样方便所有人排查和调css什么的

**Comment by donmor** [comment]
话说覆盖之后不应该刷新一下吗

**Comment by linonetwo** [comment]
我们不默认开是怕泄露商机，开源软件应该没问题的。

---

我刷新看看 ，应该就不报错了

**Comment by linonetwo** [comment]
对了，现在从firefox发送nodejs版的网页给tiddloid会闪退不知道为啥，例如太记的。不知道是文件权限问题还是nodejs版网页的HTML的问题

所以还没法流畅地firefox扫码、发送添加。还得先保存快照（nodejs版网页的特有功能）到下载目录、用文件管理器移动到别的文件夹、tiddloid打开

**Comment by donmor** [comment]
> 对了，现在从firefox发送nodejs版的网页给tiddloid会因自身空指针问题闪退不知道为啥，例如太记的。不知道是文件权限问题还是nodejs版网页的HTML的问题
> 
> 所以还没法流畅地firefox扫码、发送添加。还得先保存快照（nodejs版网页的特有功能）到下载目录、用文件管理器移动到别的文件夹、tiddloid打开
> 
> 其实要是能tiddloid直接扫码添加应该是最方便的了吧，不过用相机或者浏览器、微信扫码然后发给tiddloid成功添加应该也差不多
> 
> 试了下 https://onetwo.ren/wiki/#:Index 可以分享过去打开然后添加，果然是 nodejs 版的网页被丑拒了

问题貌似不是因为node。。刚发现HTA兼容代码出了bug导致所有以"/"结尾的url崩溃，因为getLastPathSegment居然返回了null。。下个版本修复

**Comment by donmor** [comment]
修复了
