### ISSUE TITLE
Random line of code/text appearing at bottom of page

### ISSUE THREAD

**Issue by gantrax** [donmor/Tiddloid#39]
I have various random lines of code and text appearing at the bottom of any tiddlywiki I have on tidloid for any period of time.

I noticed it the first time when I added a tiddler to Default Tiddlers. Now it has happened after forgetting to clear the search bar before either saving or closing (I am not sure which it was), and in this pic it was just after adding a "Pimsleur Japanese 1" tag to muliple tiddles

I am on a Samsung Note10 running Android 10.

I am backing up using foldersync to dropbox

![Screenshot_20220525-092902_Tiddloid](https://user-images.githubusercontent.com/106275573/170352292-64fb9b55-f247-4577-85e2-831f3ec4d664.jpg)

**Comment by mikjsmith** [comment]
I also have code appearing at the bottom of my main window:

ection ~~--> ~--> Raw markup for the bottom of the body section ~~-->

**Comment by Zacharia2** [comment]
我我我我也是，时不时的出现

**Comment by donmor** [comment]
Duplicated to #23 .
