### ISSUE TITLE
How to backup/export?

### ISSUE THREAD

**Issue by nautilus-cloud** [donmor/Tiddloid#4]
Hi - I have what may be a very basic question but I'm struggling anyway. I've been using Tiddloid happily but I can't figure out how to get my hands on my wiki file. The closest I've gotten is by exporting all tiddlers but when I open the file it looks like just one tiddler after another, none of the structure. I'm basically just trying to create a backup file that I could also use to move my wiki around to other platforms as needed. Am I missing something really obvious?

**Comment by donmor** [comment]
You can long press on the wiki and the path to the source file on your device is shown. Then you can copy the file or sync with cloud services.
