### ISSUE TITLE
Does not save on Android 12

### ISSUE THREAD

**Issue by briangular** [donmor/Tiddloid#40]
Running Tiddloid frm Fdroid on Android  12 throws a major JavaScript error when trying to save your Tiddlywiki file.

**Comment by donmor** [comment]
Any console logs? It hasn't been reproduce by me yet.

**Comment by donmor** [comment]
Okay I uploaded 2.3.0 to [GitHub](https://github.com/donmor/Tiddloid/releases/tag/2.3.0)/[Gitee](https://gitee.com/donmor/Tiddloid/releases/tag/2.3.0)/[CoolApk](https://www.coolapk.com/apk/top.donmor.tiddloid) ([F-droid](https://f-droid.org/packages/top.donmor.tiddloid/) version needs some time to be built). Try it and let me know if it ceased your problem.

**Comment by donmor** [comment]
Is there any problem now? I may close this if no problem reported.

**Comment by briangular** [comment]
This appears to be working correctly now. I can save again.
I am now running android 13 - not sure if that factors in.
From my perspective feel free to close this.

Thank you :-)

Regards,
Brian Cary
–Only 10% are Linux users. But remember, we're in the top 10%
