### ISSUE TITLE
JS issue occurring, possibly due to media query?

### ISSUE THREAD

**Issue by justin-hurd** [donmor/Tiddloid#41]
I'm no longer able to save or open/close tiddlers or my tw when using tiddloid. currently using a note 10+ running android 12, one ui 4.1

further details, image of the error and copy of the wiki located in this post made @ talk.tiddlywiki

https://talk.tiddlywiki.org/t/help-receiving-a-js-error-whenever-trying-to-use-my-tw5-on-tiddloid/3672?u=justin_h

**Comment by donmor** [comment]
To locate the problem I need the exception stack trace. Is it possible for you to have logcat fetched via adb?

**Comment by justin-hurd** [comment]
I'm not sure how to go about doing that, but if you could explain the process I can give it a try.

As far as I can tell, any time I use either of the JD Mobile plugins it causes the JavaScript error to occur. I'm going to try and reach out to JD and see if they might know the cause.

**Comment by donmor** [comment]
Get adb and install it, connect your phone to PC via usb, enable usb debugging in developer options(click version code several times or something else), open terminal and `adb devices` (there'd be a prompt on the phone, grant it) until yoy see your phone, and then you can `adb logcat` to show logs (for details you can google adb)

**Comment by justin-hurd** [comment]
[202215090110 adb-log.txt](https://github.com/donmor/Tiddloid/files/9572003/202215090110.adb-log.txt)

Will this do? 

I began the logcat, opened a fresh installation of Tiddloid on my phone, opened a tiddlywiki using the JD Mobile plugin, and triggered the JavaScript error.

**Comment by donmor** [comment]
Weirdly it contains nothing about Tiddloid.
What is that JD Mobile plugin you referred to? I didn't find any information about it. Maybe I can reproduce the error if I can get it.

**Comment by donmor** [comment]
Okay I fetched a jdmob plugin just now.
I imported this plugin to a newly-created wiki and no error occurs. File is saved successfully.
Note that I'm currently preparing for version 2.3.0, which will come with a lot of bug fixes including the most-discussed Android 10 random code bug. It is possible that the bug causing your error has been fixed.

**Comment by donmor** [comment]
Is it acceptable for you to build this app from source? You need to get android studio and android sdk, git clone the code, open the project with android studio, and finally run a debug build on your phone via usb debugging.

**Comment by donmor** [comment]
BTW your link to tiddlyhost is not clickable. Is it possible to put it here as an attachment?

**Comment by justin-hurd** [comment]
Ah, yea I fixed the link to goto a demo site rather than my personal wiki, so it should work now, it's just a clean TW with the plugin installed, no modifications made.

I can try and build it in android studio, but in the meantime, I did have a spare phone and BlueStacks available to test it, and from what I can tell I think you are right and that it might be related to the Android version that my current phone is running, because the combination of Tiddloid and JD Mobile works just fine on other devices.

The current version of Android my phone (Samsung Galaxy Note 10+) is running is Android 12 though, rather than Android 10. Do you know of any known bugs with Android 12?

**Comment by donmor** [comment]
#23 Since Android 10, currently reported the most.

**Comment by justin-hurd** [comment]
So, I've imported it into Android Studio, but I'm unable to build it because of something called a Gradle Sync Issue.

I'm not familiar with App Development unfortunately, so I'm not sure how to proceed from here, do you have any suggestions?

**Comment by donmor** [comment]
To build the apk you need a cert. Do some google stuff(android studio sign your app) and you'll know what to do.

**Comment by donmor** [comment]
Okay I uploaded 2.3.0 to [GitHub](https://github.com/donmor/Tiddloid/releases/tag/2.3.0)/[Gitee](https://gitee.com/donmor/Tiddloid/releases/tag/2.3.0)/[CoolApk](https://www.coolapk.com/apk/top.donmor.tiddloid) ([F-droid](https://f-droid.org/packages/top.donmor.tiddloid/) version needs some time to be built). Try it and let me know if it ceased your problem.

**Comment by justin-hurd** [comment]
Sorry for the delay, I've been preoccupied with work; I had a moment to test the new version and unfortunately the JS error still persists.

**Comment by donmor** [comment]
Tried your file on Tiddloid 2.3.0 on android 13. The file is not able to be saved, prompting `Starting to save wiki`. Successfully saved after removing configurations in `TiddlySpot Saver`. No JS error occurred. Weird enough :(

**Comment by justin-hurd** [comment]
I'm starting to think it is an issue with either Android 12, or with my model of phone, rather than the app itself or TiddlyWiki.

However I'm not sure how to test for either of those :\

**Comment by justin-hurd** [comment]
I haven't been in use of Tiddloid, and instead moved to hosting my TW on TiddlyHost, so I do not have an update on the matter unfortunately. I will go ahead and close with this comment, thank you for your help though
