### ISSUE TITLE
Importing a Tiddlywiki from a url

### ISSUE THREAD

**Issue by myfta** [donmor/Tiddloid#42]
In the notes it says "Receiving a TiddlyWiki site URL shared from Browser and save as a new file or a bookmark" but I cannot see where the URL is entered in the App.

Please advise.

**Comment by donmor** [comment]
Open the URL in your browser, click "Share" in menu, then choose "Add to Tiddloid" here. Literally.

**Comment by linonetwo** [comment]
这个会导致闪退，导入失败，能复现吗？

**Comment by donmor** [comment]
是不是以/结尾不带index.html的网址？已经修了，下个版本就好

**Comment by linonetwo** [comment]
是类似 http://10.68.53.252:5214/#%E5%9C%A8%E5%AD%97%E8%8A%82%E5%90%83%E5%88%B0%E7%9A%84%E5%A5%BD%E5%90%83%E7%9A%84%E9%9B%B6%E9%A3%9F  这样的网址，多文件版提供的，然后我是希望导入进 tiddloid 变成单文件，然后用 https://github.com/tiddly-gittly/tw-mobile-sync 来同步

**Comment by linonetwo** [comment]
![](https://user-images.githubusercontent.com/3746270/190861101-404bead1-181a-4fea-9c2a-17030fe5df23.png)

这咋办，我又跑不起来了

**Comment by linonetwo** [comment]
![](https://user-images.githubusercontent.com/3746270/190861148-670b358d-5f93-4e8c-951d-64d703cac839.png)

**Comment by donmor** [comment]
az……你看看你local.properties还在不在

**Comment by linonetwo** [comment]
为了拉代码我都删了，我回顾一下之前是咋整的，太久没编译android了

**Comment by donmor** [comment]
这边应该是没什么问题了罢（

**Comment by linonetwo** [comment]
其实有时候还是会 null poinger 闪退，我今天看看

**Comment by linonetwo** [comment]
又无法复现了，先关了吧。

最好能把 log 放在某个地方，方便提交 issue 排查。

**Comment by donmor** [comment]
行吧。。另外可以看看我发的2.5.0pre
