### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#44]
Hide the titlebar.

全屏展示完整html内容，其实app的顶部栏不是很常用，要是能一直收起（甚至上下滑时也不展示）就好了。例如保存按钮其实可以靠太微内的下载保存按钮来取代了。

**Comment by donmor** [comment]
wiki更多菜单里面有个全屏，直接按就行了。。大概好像是

**Comment by linonetwo** [comment]
不大行啊，点了会变成横屏全屏。反正竖屏状态上面那个条是一直在那，显示的按钮也和wiki内的按钮和标题重复了

**Comment by donmor** [comment]
哦对 FAQ里面有一条就是

```
如何调整界面？

导入随apk提供的插件并：

应用主题色：选中Control Panel/Appearance/Tiddloid Tweaks/Apply theme color to system bars。
隐藏标题栏：选中Control Panel/Appearance/Tiddloid Tweaks/Hide toolbar on loading complete。
自定义菜单项：在Control Panel/Appearance/Tiddloid Tweaks中点击Custom Actions创建配置Tiddler，并按提示编辑。
```

**Comment by linonetwo** [comment]
我懂了，你提供了JSB供JS插件调用来调整显示样式，那可以的。不过没在 release 里吧，是在哪里啊？

也可以我有空上传到 CPL 去。

**Comment by donmor** [comment]
应该是在以前的release里面

**Comment by donmor** [comment]
一会更新一下直接把这个插件塞assets里得了XD

**Comment by linonetwo** [comment]
其实放一个稳定下载链接，然后传 CPL 最好啊

稳定下载链接参考 https://github.com/felixhayashi/TW5-TiddlyMap/issues/430

**Comment by linonetwo** [comment]
[https://github.com/donmor/Tiddloid/blob/master/app/src/main/assets/tiddloid-tweaks-plugin.tid](https://github.com/donmor/Tiddloid/blob/master/app/src/main/assets/tiddloid-tweaks-plugin.tid) 这个有源码仓库吗

**Comment by donmor** [comment]
看样子这边应该可以关了
