### ISSUE TITLE
建议：如果tiddloid使用webdav数据中心化，或许会是一个好的想法。

### ISSUE THREAD

**Issue by Zacharia2** [donmor/Tiddloid#46]
以webdav服务器框架为文件读写基础搭建的tiddloid或许会解决文件系统的一切奇怪问题。
整体架构webdav服务器（Milton➕Web服务器）➕WebView➕历史版本备份➕列表视图布局。

![image](https://user-images.githubusercontent.com/32425955/183773718-f33906f8-cfc3-44a9-ae51-dd677e010d3c.png)

平时我们可以使用手机记录信息，等到有桌面端时，我们可以使用桌面端的浏览器进行修改整理，所以多平台的扩展性也是一个非常方便的事情。据我所知，使用webdav Pro这个webdav服务器安卓软件在任何情况下保存TiddlyWiki都没有任何问题。或许可以解决文件系统的访问带来的乱码问题。（不知道的是，是否支持TiddlyWiki文件夹，但一定支持html单文件TiddlyWiki。）

其中一，webdav框架可以实现任意位置浏览器访问。为多端同步提供可能性，增加易用性，或许可以替代印象笔记加obsidian。

其二，webdav支持图片上传到文件夹。
其三，webdav安卓框架有现成的名叫Milton2。或许可以快速搭建。
其四，让整体性感增加，集中软件功能优化使用体验，后期的优化或许更加容易。

其五 可以实现局域网内使用任意浏览器快捷访问太微文件列表。修改使用。
其六，数据携带容易。拥有webdav服务后 ，不用在受制于手机的局限，可以任意使用其它设备的浏览器和功能，并且中心服务器的好处是，可以作为一本书一样，将其它所有的笔记全部装进TiddlyWiki。（或许）。

附加开源库：
AndroidWebServer ：https://github.com/lopspower/AndroidWebServer/pulls
android-viewflow：https://github.com/pakerfeldt/android-viewflow
milton2：https://github.com/miltonio/milton2

**Comment by donmor** [comment]
不管什么程序，只要数据还在手机上就绕不开存储bug= =
如果用file协议，那还不如直接legacy模式
下一步我可能把雪藏的legacy模式重新加到界面上，然后平时直接legacy模式读写，需要远程访问时单独开webdav服务器

**Comment by Zacharia2** [comment]
![Screenshot_2022-08-10-08-31-44-818_com theolivetree webdavserverpro](https://user-images.githubusercontent.com/32425955/183784875-51e3ea91-f3fd-4975-84df-e119e70cc12b.jpg)
哦是这样呀，谢谢你，嗯，我现在用的这个webdav服务器软件，似乎没有出现过问题，不知道为什么没问题。唯一的不好就是感觉太散了。。。嘿嘿

**Comment by Zacharia2** [comment]
哦对，我刚刚想起来，使用tiddloid的webdav客户端➕ webdav Pro确实问题没有得到解决。

不过单纯使用webdav Pro服务器却完全没有问题发生。

**Comment by donmor** [comment]
最近做了个patch，Android11以上每次开文件会强制加载整个文件进内存，然后跳过第一个`</html>`以后的所有内容（即乱码）
缺点是几十兆的大文件会OOM :(

**Comment by donmor** [comment]
以及只有Tiddloid上看不到乱码，其他的乱码还在=。=但是拷到Android10及以下系统保存一次确实可以消除乱码

**Comment by donmor** [comment]
更正：Android 10 也受影响，patch改为Android 9及以上生效

**Comment by linonetwo** [comment]
几十兆的文件咋就OOM了

**Comment by donmor** [comment]
更新：有大能提了彻底解决的方案，正在实验中

**Comment by donmor** [comment]
再更：2.3.0出了，应该已经解决

**Comment by Zacharia2** [comment]
赞👍🏻👍🏻👍🏻
