### ISSUE TITLE
HTML5 audio tag not working

### ISSUE THREAD

**Issue by leoperbo** [donmor/Tiddloid#5]
I have tiddlers with code similar to:
`<audio src="media/mozart.mp3" controls />`

In Firefox (Android and Linux) those tiddlers renders like this:
![Screenshot_2020-03-04-11-30-58-616_org mozilla firefox](https://user-images.githubusercontent.com/13077338/75906401-46e12480-5e0c-11ea-8171-761e248b9458.png)
And audio plays without problems.

But in Tiddloid (and browsers based in Blink engine like Chromium and Chrome) I get this:
![Screenshot_2020-03-04-11-29-46-320_top donmor tiddloid](https://user-images.githubusercontent.com/13077338/75906602-8f98dd80-5e0c-11ea-9800-9af9d8ab6840.png)
And audio can't be played.

I had tried with the more complex versions of code for HTML5 audio tag...
Like this:
`<audio src="media/mozart.mp3" type="audio/mpeg" controls />`

Or like this:
```
<audio controls>
    <source src="media/mozart.mp3" type="audio/mpeg">
    <source src="media/mozart.ogg" type="audio/ogg">
Your browser doesn't support the media type.
</audio>
```

A very wide range of combinations, but none allowed me to play my audio tiddlers in nothing based in Blink engine (like Tiddloid).

In deed, in Firefox, tiddlers set as media type with  the field __canonical_uri_ pointed to an audio file shows the audio controls and plays the sound like a charm:
![Screenshot_2020-03-04-11-44-03-264_org mozilla firefox](https://user-images.githubusercontent.com/13077338/75907379-cc190900-5e0d-11ea-89a5-594f87adfce7.png)

Any chances to find a solution to make HTML5 audio tag to work in Tiddloid or to port it to Mozilla's Gecko engine?

**Comment by donmor** [comment]
Hi leoperbo,
Sorry but I can't see the pictures 'cause githubusercontent.com is out of access in China. But uploading this is possible:
![S00305-02352234](https://user-images.githubusercontent.com/29735136/75911188-248dec00-5e8a-11ea-86ed-e48876fa2938.png)
I tested my latest release on my device and nothing goes wrong. The audio just plays.
It is possible that issues in Android System Webview caused the problem, since Tiddloid uses it as its core. Did you try running the app or the wiki on another device?
donmor

**Comment by leoperbo** [comment]
I'll try in another devices, your comment about Android System Webview makes sense.
Thank you for the fast answer!

**Comment by leoperbo** [comment]
I have tried disabling Chrome engine as WebView in my Xiaomi Redmi Note 5 and enabling Android System WebView version 80.0.3987.132 with no luck. Will try in another device.

**Comment by donmor** [comment]
Too long time waiting for a response. Closing.
