### ISSUE TITLE
 2.4.X版本的$:/favicon.ico图标问题

### ISSUE THREAD

**Issue by Zacharia2** [donmor/Tiddloid#52]
从2.3.1升级后打开直接闪退，原先版本有wiki存在。

清空数据，导入wiki，保存重新打开闪退。

**Comment by Zacharia2** [comment]
红米note10Pro

**Comment by donmor** [comment]
清数据然后新建一个wiki呢

**Comment by donmor** [comment]
如果不崩的话能不能发一下那个文件我debug一下

**Comment by donmor** [comment]
。。我自己的也崩了。。前两天还好用的，我自己先弄一下吧

**Comment by donmor** [comment]
你的文件是不是用了svg图标？新加的功能，应该是有bug

**Comment by donmor** [comment]
已经定位问题，马上修复上传

**Comment by donmor** [comment]
2.4.1已发布

**Comment by Zacharia2** [comment]
赞👍🏻👍🏻👍🏻

**Comment by Zacharia2** [comment]
不好意思啊，最近忘记看issue了，在为太记配置开发环境😂

**Comment by Zacharia2** [comment]
我的文件没有用SVG，清除后新建一个也是一样的。

**Comment by Zacharia2** [comment]
安装了2.4.1版本，闪退没有了，但png格式的$:/favicon.ico也不显示了，image/x-icon格式的图标倒是显示的。

**Comment by donmor** [comment]
行吧。。。我再看看

**Comment by Zacharia2** [comment]
辛苦了，辛苦了🌹🌹🌹

**Comment by donmor** [comment]
问题已定位，检查base64的正则漏了等号，一会更新

**Comment by Zacharia2** [comment]
赞٩(*´◒`*)۶

**Comment by Zacharia2** [comment]
赞👍🏻👍🏻👍🏻
