### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by ghost** [donmor/Tiddloid#53]
Hi all.

I wonder if you've all thought about adding support for a cloud service like Dropbox, Google-drive or tiddlyhost in Tiddloid. *Have you all thought about adding support for a cloud service like Dropbox, Google-drive, tiddlyhost or protocols as ftp, sftp in Tiddloid?*

**Comment by donmor** [comment]
I prefer using DocumentProvider(SAF). This makes all cloud services accessible from Tiddloid as long as their app is installed.

Another way is to use WebDAV which is currently supported.

To use tiddlyhost you may try adding the url to the app as a bookmark.

Remember to report any problem :)

**Comment by donmor** [comment]
Nope. I use F-Droid instead.

**Comment by donmor** [comment]
Hmmmmmmmmmmmmmmmmmmmmmm... One of the least common needs. It's way too uncommon to make this for everyone.

**Comment by donmor** [comment]
Already there. See FAQ for instructions.

**Comment by donmor** [comment]
Hmmm... Rather new and flexible? XD
