### ISSUE TITLE
2.4.0

### ISSUE THREAD

**Issue by TechLifeWeb** [donmor/Tiddloid#54]
I have a Pixel 3 and 2.4.0 won't open. It tries to but then just closes. I downgraded back to 2.3.1 and it is fine.

**Comment by donmor** [comment]
Fixed in 2.4.1

**Comment by donmor** [comment]
Is there any problem now? I may close this if no problem reported.

**Comment by donmor** [comment]
No more reports for 3 months. Closing this. Reopen it if you're still concerned.
