### ISSUE TITLE
won't save

### ISSUE THREAD

**Issue by nathgit** [donmor/Tiddloid#55]
Everytime I save, it acts like it's saving but when I get out of it & go back in, it displays a message saying the wiki already exists. If I open the file directly from the file manager, it loads the original copy. I tried creating a tiddler to test backup & restore & it says it's not valid JSON.

**Comment by nathgit** [comment]
I checked the timestamp on the html file & it says it was just updated, but when I open it again in tiddloid, it says the file doesn't exist.

**Comment by nathgit** [comment]
the imported files do get saved, but I have to search for them to find them, because they don't appear in the list of tiddlers.

**Comment by nathgit** [comment]
I tried again & for some reason it saved the new Tiddler & imported it successfully, but once again I had to search to find it. The Jason error it was giving when trying to import was because the file already existed. I simply couldn't see it. I think the problem with saving _**may**_ be that I was using the save button in the app itself instead the built-in button in the file itself which tiddlywiki tells you to use, because that is the only way that will work. Hopefully it will work right from now on.

**Comment by nathgit** [comment]
Now the import isn't working again. when it tried to import it instead creates a new tiddler with the error "JSON error: SyntaxError: Unexpected token '<', " <!doctype "... is not valid JSON", which is the error I was getting before. I did a search for the name of the tiddler as I did before & it doesn't exist.

**Comment by donmor** [comment]
What varsion of wiki/app are you using? And android version of your device? I can't reproduce it on my phone right now
