### ISSUE TITLE
How to install third party plugins?

### ISSUE THREAD

**Issue by toolonely** [donmor/Tiddloid#56]
So there's a TiddlyWiki opened in Tiddloid, and a third party plugin opened in a web browser app. On desktop, where the wiki is opened in a browser as well, it is recommended to place the windows next to each other and drag the plugin into the TiddlyWiki. How to do it on an Android phone?

**Comment by donmor** [comment]
Export the plugin in browser by clicking ﹀on the plugin tiddler and choose `export` > `.tid file`, then import this file into the wiki in Tiddloid.

**Comment by toolonely** [comment]
@donmor Tried your suggestion with https://benwebber.github.io/tiddlywiki-plugins/#crosslinks

This is the content of the .tid file, which Tiddloid fails to import:

```
list: Overview History [[View Templates]]
tags: Plugin
title: crosslinks
```

I get a similar result when trying to export as JSON:

```
[{"title":"crosslinks","tags":"Plugin","list":"Overview History [[View Templates]]"}]
```

What am I doing wrong?

**Comment by donmor** [comment]
When I say a plugin to be exported, I mean something like `$:/plugins/benwebber/crosslinks` bro :)

**Comment by donmor** [comment]
The plugin you arr trying to export is not properly packed. All of its contents are outside the plugin tiddler. You may try exporting all the tiddlers in its content page and then import the all by once :)

**Comment by toolonely** [comment]
The above suggestion worked, thank you. (I did not get the crosslinks in tiddlers, but that's beyond the scope of the original question) Feel free to close the issue.

**Comment by linonetwo** [comment]
you can use [https://github.com/tiddly-gittly/TiddlyWiki-CPL](https://github.com/tiddly-gittly/TiddlyWiki-CPL) to install plugins
