### ISSUE TITLE
App crashes when opening a url

### ISSUE THREAD

**Issue by myfta** [donmor/Tiddloid#58]
I can pass a Tiddlywiki url from my browser OK and Tiddloid briefly opens the page and then crashes. I have the same problem on two different Android devices.

**Comment by donmor** [comment]
Is there any details? For example, the url you passed to it.

**Comment by donmor** [comment]
I tried some URLs, either a wiki page loaded, or prompted that a non-wiki URL passed. No crash occurred.

**Comment by donmor** [comment]
Does anyone still have problem with 2.3.0 or later? I may close this if no problem reported.
