### ISSUE TITLE
favicon will appear maximised regardless of size

### ISSUE THREAD

**Issue by edo0** [donmor/Tiddloid#59]
As per the title, when opening my tiddlywiki which has a (defined as) 16*16 svg favicon, it will render in a way that occupies most of the screen and cannot be collapsed or hidden in any way.
I am using the latest tiddloid version (2.4.2) and the latest tiddlywiki (5.2.4)

![Screenshot_20221215-231229_Tiddloid](https://user-images.githubusercontent.com/16632292/207987166-bd73bc54-f5b2-410f-81c5-07d9836778bb.png)

Thank you very much for the app, keep up the great work, and do let me know if I can help debugging this further

**Comment by donmor** [comment]
Can you upload the file causing this? I thought I fixed this in 2.4.2 and it no longer occurs on my system.
![Screenshot_1678003011](https://user-images.githubusercontent.com/29735136/222948894-93dfd26c-ec47-4545-9e72-390fd4afa0c7.png)

**Comment by donmor** [comment]
Okay I think I found the reason and it'll be fixed in next version :-)

**Comment by donmor** [comment]
Now you can try [this](https://github.com/donmor/Tiddloid/releases/tag/2.5.0-pre) if you'd like to.

**Comment by edo0** [comment]
Thank you very much.
I have tried the pre-release for 2.5.0 you linked, and it fixes this issue perfectly!
