### ISSUE TITLE
External Google drive links do not render

### ISSUE THREAD

**Issue by jorgb** [donmor/Tiddloid#6]
Hi, when I link an external image I can do so with an external tiddler or [img[]] link. However, when renderered in Tiddloid Lite I do not see an image. When I open the TiddlyWiki in Chrome with the same content, it loads. Can this be fixed? I want to add drawings to a personal gallery that are too large to keep inside of Tiddlywiki itself. 

The uri for example is;

https://drive.google.com/uc?export=view&id={ID} 

This link is obtained sharing privately in Google Drive. Is there a way to piggyback off chrome which shares a session with my Google drive?

**Comment by donmor** [comment]
Hi jorgb, 
The Storage Access Framework that Lite uses prevents the app from accessing files other than the wiki HTML itself. One of the solutions is to upload your pictures to an image hosting site and use the URL from there.

**Comment by jorgb** [comment]
Hi,

Thank you for your reply. When I tested the tiddlywiki site in the Samsung
Browser I hit the same wall. It appears because chrome is signed in to my
Google account it let's me see the private links.

My solution for now is migrating to Dropbox as the private link solution
does work for Tiddloid.

Thanks,
- Jorgen
