### ISSUE TITLE
slow to load large file

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#61]
![Screenshot_2023-02-08-11-28-12-300_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/3746270/217452727-157e1b47-e456-4989-bf1b-e65699b0c43e.jpg)

250M with lots of image, take 30s to load.

**Comment by donmor** [comment]
好吧。。不如说以现在这个app架构，打开200多m没oom挂掉也是nb（
主要Tiddloid本身单文件模式可能就没针对超大文件设计过。。图多的话可以改目录模式或legacy模式，把图放index.html外面
要是单纯文字撑到200多m那还是上node吧😂想不到什么别的方法

**Comment by linonetwo** [comment]
其实直接通过分享，从浏览器分享给tiddloid添加会闪退。不过我先下载再载入就还好。

其实主要是 PDF 比较大，我试试在同步时把 PDF 去掉

**Comment by linonetwo** [comment]
其实解决 https://github.com/donmor/Tiddloid/issues/60 也能解决这个问题，不需要重新载入就好了
