### ISSUE TITLE
Feature request: Share link to TW

### ISSUE THREAD

**Issue by mwestenthanner** [donmor/Tiddloid#63]
Hello,

I have a feature request and hope this is possible.

Desired app behavior: When I share a link (e.g. a reddit post) via the share sheet and it's not a Tiddlywiki, I can paste into a new tiddler.

Current app behavior: Tiddloid tells me that this page is not a TW and cancels the whole action. 

Suggestion: Maybe the warning message could include a button "Paste into tiddler" or something similar so saving links via Tiddloid is easily possible. Thank you!

**Comment by donmor** [comment]
If you open a wiki and put the app in background, then all text content sent to it will become a tiddler. See FAQ for details.
