### ISSUE TITLE
不该允许「添加文件夹」选择html文件

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#66]
注意看，这个用户叫做小帅，他尝试添加下载的HTML文件到太卓。他第一步选择了「添加文件夹」，然后他选择了一个HTML文件。

https://user-images.githubusercontent.com/3746270/223464470-9bffc57e-2aad-4ff3-9775-1d7cc1cae603.mp4

当他再次尝试点开这个列表里的wiki，发现无法打开了。

---

后来他发现第一步应该选添加文件

https://user-images.githubusercontent.com/3746270/223464899-1b6c71e8-ab24-4ec4-8586-a262130dfa08.mp4

**Comment by donmor** [comment]
啊这。。只能问问鼓哥为什么搞出这种设计了😂以及不要点文件右边那个键，那是预览（估计打开一次uri就作废那种，用来在选择文件前确认的）

**Comment by linonetwo** [comment]
添加 HTML 文件的 icon 应该是文件，而不是个文件夹

还有添加文件夹的功能，会创建一个新的 wiki 文件，而不会导入文件夹里所有的 html

**Comment by donmor** [comment]
> 添加 HTML 文件的 icon 应该是文件，而不是个文件夹
> 
> 还有添加文件夹的功能，会创建一个新的 wiki 文件，而不会导入文件夹里所有的 html

啊这，我直接加了图标库里的图标的😂
以及如果目录里有index.gtml会直接沿用

**Comment by linonetwo** [comment]
我在文件夹里自己存的是 wiki.html ，就没有用起来过

**Comment by donmor** [comment]
嘛，我想想能不能以某种方式允许非index.html文件名作首页罢（

**Comment by donmor** [comment]
比如读取.htaccess

**Comment by linonetwo** [comment]
这个是什么文件？难道不能直接读取文件夹里，所有HTML，然后走导入文件流程吗

**Comment by donmor** [comment]
这个目录模式当时好像是给网站结构设计的，为了兼容saf，能给文件管理权限还是legacy好用

**Comment by donmor** [comment]
2.5.0出了，丢一个下面这种文件进去命名为`.htaccess`应该可以改变首页
```
<IfModule dir_module>
DirectoryIndex wiki.html
</IfModule>
```
~~其实只需要中间那行就行了~~

**Comment by linonetwo** [comment]
好的，这种有点极客的东西得宣传一下大家才能用起来了，这个当时好像是QQ群友反馈的，也不知道他还有没有在用太微了…

**Comment by linonetwo** [comment]
我最近是在用 https://github.com/tiddly-gittly/TidGi-Mobile 了，因为 HTML 版打开我 1GB 的wiki太慢了，我现在用SQL存储，而且还是流式加载的，不然实在卡得不行。

对了，你QQ上私聊我一下，方便我加个好友或者备注一下啊。

**Comment by donmor** [comment]
后面估计年更了😂太忙
