### ISSUE TITLE
hide toolbar not working in tw v5.2.6

### ISSUE THREAD

**Issue by mc96107** [donmor/Tiddloid#67]
1. created a fresh tw from tiddloid 2.4.2
2. installed tiddloid tweaks plugin
3. enabled hide toolbar
4. saved and opened the wiki, tiddloid toolbar was still visible.

**Comment by donmor** [comment]
Crap... Plugin auto update also broken. I'll work on this later.

**Comment by donmor** [comment]
Version 2.5.0 released. Be sure to try it out and tell me if it solved your problem :)

**Comment by mc96107** [comment]
Yes, thank you very much!
