### ISSUE TITLE
async save

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#69]
现在保存时，会卡一下。

如果改成用 worker 在后台保存，并搞个队列防止数据竞争，就可以保存大文件也不卡了。

**Comment by donmor** [comment]
目前不确定这种底层改动需要的工作量_(:з」∠)_最近工作比较忙，够呛能抽时间搞了

**Comment by linonetwo** [comment]
只好暂且用着了。

或者如果能用 localstorage/indexeddb 的话，就不需要保存了，直接暂存里面，然后定期同步回电脑上的太记就好了

**Comment by linonetwo** [comment]
同 https://github.com/donmor/Tiddloid/issues/70 ，关键还是让保存不卡。
