### ISSUE TITLE
[feature request] hide the android app-wrapper topbar, or allow a wiki to add a button to it

### ISSUE THREAD

**Issue by jdjdjdjdjdjd** [donmor/Tiddloid#7]
Hi! I love this android app, it's been the mobile home of my wikis for so long now! But I have a request regarding Tiddloid's topbar inside a launched wiki.

Can it be hidden? I access my wikis through Tiddloid's homescreen-shortcut-to-wiki feature and have no need for the single interactive thing on the topbar (the ← back button).

Or an alternative if hiding it is impossible, can you let a wiki insert an object to the topbar? For example: in a wiki, I may have a NewTiddlerButton tagged "$:/tags/TiddloidTopbar", which I hope will appear at the topbar of Tiddloid when that specific wiki is launched. Maybe up to three buttons can be tagged this way and show up in the Tiddloid topbar. Is this possible?

Thanks so much for this wonderful app!^^,

**Comment by donmor** [comment]
By default the toolbar is hidden under landscape layout. 
As for the toolbar buttons, I'm not sure what you want it to do with the toolbar buttons, since the H5 side, known as TiddlyWiki, is not maintained by me, and by the time I'm not been so deep in world of H5.

**Comment by jdjdjdjdjdjd** [comment]
Thanks for the quick replies!

> By default the toolbar is hidden under landscape layout.

Can this also be an option in _portrait_ mode? I rarely use my phone landscape

> As for the toolbar buttons, I'm not sure what you want it to do with the toolbar buttons, since the H5 side, known as TiddlyWiki, is not maintained by me, and by the time I'm not been so deep in world of H5.

I meant Tiddloid's / TiddloidLite's topbar itself. Currently it shows "← WikiName   " and nothing else. 

I was wondering if it's possible to add a button to it, sample: in WikiName.html I have a tiddler tagged $:/tags/TiddloidTopbar, can TiddloidLite retrieve that button, add that to the TiddloidLite topbar when WikiName.html is open, then when that button is clicked, allow that button to interact with WikiName.html? The button tagged $:/tags/TiddloidTopbar is not universally available on all wikis, just the wiki where it is stored. 

But, this was just an alternative idea if it's not possible to hide TiddloidLite's topbar in portrait mode, my main request.

**Comment by donmor** [comment]
Well, I'll consider add a feature that HTMLs with special tiddlers could change the behavior of the app. For example, in $:/Tiddloid.conf, "hideToolbarPortrait=yes" hides the toolbar under portrait mode. 
As for the buttons on the toolbar, what do you wish to happen if the buttons clicked? 
Btw parsing the whole wiki for the tagged tiddlers could take long time.

**Comment by jdjdjdjdjdjd** [comment]
> Well, I'll consider adding a feature that HTMLs with special tiddlers could change the behavior of the app. For example, in $:/Tiddloid.conf, "hideToolbarPortrait=yes" hides the toolbar under portrait mode.

Just this addition will satisfy all my related requests!^^,

> As for the buttons on the toolbar, what do you wish to happen if the buttons clicked?

Since the idea is that it will interact only with the wiki containing it, then the usual actions that can be defined inside a button, I hope. Sample: I have a very customized Journal button, the idea was to just add a tag to it so it will appear in Tiddloid's topbar, and it will perform its actions on the wiki containing it, once clicked.

Again, this was just in case the hideToolbarPortrait option wasn't feasible... as a way to make it, if not hide-able, then interactive.

> Btw parsing the whole wiki for the tagged tiddlers could take long time.

Thanks for the heads-up! If that will be the case, then I'm perfectly happy with just the ability to hide the Tiddloid topbar, since, inside of TW itself, I can create a more customized one.

**Comment by donmor** [comment]
Okay. By now I'm trying to implement in file configuration first, and then try the button stuff in future updates.

**Comment by donmor** [comment]
The 2.1.0 has been released. I think it has met most of your requirements.
