### ISSUE TITLE
save on blur

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#70]
这样就可以不开自动保存，再切换到其他应用的时候自动让它保存。
主要是开了自动保存，保存起来，实在是太卡了

**Comment by donmor** [comment]
没明白😂安卓切后台webview会暂停活动的吧，TiddlyWiki保存需要自身js运行才行

**Comment by linonetwo** [comment]
Java 不能直接触发保存吗，直接发起一个保存的 tm-xxx 就好了。

还有这个应该是在常驻后台的时候用的

**Comment by donmor** [comment]
貌似触发不了_(:з」∠)_发起js是异步的，不等响应activity就冻了
以及webview和其所在activity不在前台基本可以认为不存在😂

**Comment by linonetwo** [comment]
好吧，那看来关键还是后台保活+有变化的时候及时同步吧。

不对啊，为啥cdda有这个功能呢？我在他的设置里看到就有一个在失去焦点时自动保存

**Comment by linonetwo** [comment]
![Screenshot_20230620153009.jpg](https://github.com/donmor/Tiddloid/assets/3746270/9a93e17d-4e16-4a48-ba18-37d4ea898ecb)

**Comment by donmor** [comment]
这是什么，没见过_(:зゝ∠)_
如果不涉及异步的话就可以做的，然而^q^

**Comment by linonetwo** [comment]
https://github.com/tiddly-gittly/TidGi-Mobile 用 sync Adaptor 功能，写一点就保存到 SQLite 一点，就快多了
