### ISSUE TITLE
Sort/search for wikis from the home screen

### ISSUE THREAD

**Issue by naveenroyv** [donmor/Tiddloid#71]
Hi there,
Love the app. Just a feature request please, I have a number of wiki htmls (around 55) that I use - if you could add sorting or searching features on the home screen that would make it perfect (for me) to use. Thanks.

**Comment by donmor** [comment]
I'll consider it.

**Comment by donmor** [comment]
Version 2.5.0 released. Be sure to try it out and tell me if it solved your problem :)

**Comment by naveenroyv** [comment]
Thanks, installing the apk directly seems to crash (on my Pixel 6 pro). I see the update hasn't made its way to f-droid, will install when I see it available there. Thanks again for your continued development towards the app!

**Comment by donmor** [comment]
Yeah you have to update from f-droid if you downloaded there, since they build apks from source and use their own signature XD

**Comment by naveenroyv** [comment]
Thanks, works perfectly!
