### ISSUE TITLE
internal JavaScript error

### ISSUE THREAD

**Issue by IngoBelka** [donmor/Tiddloid#72]
My system:
* Huawei Media Pad 9
* Android 9
* Tiddloid 2.4.2 (F-Droid store)

The problem:
Every second edit of a tiddler I get a JavaScript error and the changes can't get saved. I have to close Tiddloid and restart to make the next edit and to save then. This way to use is a bit difficult.
Might it be, that this has to do with the new Tiddlywiki version 5.3.0?

**Comment by donmor** [comment]
I'm working on 5.3.0 (WIP) and cannot reproduce your problem. You can try 5.3.0 once released.

**Comment by IngoBelka** [comment]
I did further tests and I see this behaviour only with wikis converted from 5.2.3 to 5.3.0. A wiki new created with Tiddloid works normal. Perhaps this leads to the problem?

**Comment by donmor** [comment]
Does this appear on TiddlyDesktop? You may push an issue to Jermolene/TiddlyWiki5.

**Comment by IngoBelka** [comment]
I'd made the update to version 5.3.2. The JavaScript Error has gone now, but I can't say, if the update is the reason why.
For me the problem is solved now.
