### ISSUE TITLE
Images not displaying when loading via _canonical_uri

### ISSUE THREAD

**Issue by naveenroyv** [donmor/Tiddloid#73]
Hi there,
I've noticed that images stored in a directory containing my html file are not displayed when using the _canonical_uri field - appears to be a potential bug, please could this be fixed? Picture loads okay when opening the html file via a browser.

**Comment by donmor** [comment]
Are you using legacy mode? Currently only legacy mode and directory mode support this

**Comment by naveenroyv** [comment]
Thanks, switching to legacy mode sorted the issue out.
