### ISSUE TITLE
无法打开QQ群分享的HTML

### ISSUE THREAD

**Issue by linonetwo** [donmor/Tiddloid#77]
![Screenshot_2024-02-05-12-03-51-311_com.tencent.mobileqq.jpg](https://github.com/donmor/Tiddloid/assets/3746270/86f31fa7-d58a-4f42-b418-a4cfad898f59)

![Image_1707106032271.jpg](https://github.com/donmor/Tiddloid/assets/3746270/2bda172b-b328-4d68-a9e6-1b68a10e8fe4)

虽然实际上打开了，但他以为自己没打开，所以就要求删除

**Comment by donmor** [comment]
QQ我没装😂TIM出来的uri貌似是一次性而且不可写入的，这种最好是另存出来

**Comment by linonetwo** [comment]
我发现了，太微导出单个条目是静态HTML！缺乏导出正常HTML的功能，真可惜！
