### ISSUE TITLE
[feature request] sync with Google Drive

### ISSUE THREAD

**Issue by jdjdjdjdjdjd** [donmor/Tiddloid#8]
Hi, I know I can just keep on using the GoogleDrive sync app I have, but can Tiddloid have this as a native feature? Where the wiki is still available offline for editting, but when online, can detect and sync changes to GoogleDrive?

**Comment by donmor** [comment]
Try using [Tiddloid Lite](https://github.com/donmor/TiddloidLite) instead. 
Based on SAF, this branch can access any cloud drives like Gdrive and Onedrive.

**Comment by jdjdjdjdjdjd** [comment]
Oh my, thanks! I just tested it and it works well, synced offline changes from my phone once it went back online.

By the way, it seems I've posted these issues on the wrong project! I'm using Tiddloid LITE
