### ISSUE TITLE
[feature request] faster load time

### ISSUE THREAD

**Issue by jdjdjdjdjdjd** [donmor/Tiddloid#9]
Hi, Tiddloid is fast enough as it is, but launching GoogleKeep is _still_ faster than opening a wiki shortcut. 

Can this be improved, or is it already as fast as Android allows?

**Comment by donmor** [comment]
Usually an app based on H5 is slightly slower than an app that is "native".
Anyway, I'll keep improving the performance of my apps.

**Comment by jdjdjdjdjdjd** [comment]
Oh, thanks for the fast replies and for the continuous development!
